### ISSUE TITLE
Adapt to claim $blur airdrop

### ISSUE THREAD

**Issue by facies** [script-money/ens-claim-flashbot-example#26]
Hello,

I try to help a friend who can't claim $blur on a compromised wallet. Can the src/engine/ENS.ts script be adapted to claim and transfer $blur?

The Blur contract is https://etherscan.io/address/0xf2d15c0a89428c9251d71a0e29b39ff1e86bce25

Thank you for your help!

**Comment by script-money** [comment]
When you claim airdrop from blur.io, you can find a request ending with "claim" from the network in developer tools.
This request will return "data", send the data to contract address will claim all your tokens, no need ABI.
You can try it yourself first, if you still can't solve it, I will update the code in the coming days.

**Comment by facies** [comment]
Thanks for your answer. Actually I already claimed my airdrop so I need to find someone who can provide the data code.

**Comment by script-money** [comment]
check https://github.com/script-money/ens-claim-flashbot-example/commit/44c5a6a827598b08feef98fbf7253c6dafcb3d8c

**Comment by facies** [comment]
Thanks a lot for releasing this. I am experiencing the following error when I do the npm install 

node_modules/keccak256/dist/keccak256.d.ts:4:67 - error TS2749: 'buffer.Buffer' refers to a value, but is being used as a type here. Did you mean 'typeof buffer.Buffer'?

I tried to do a npm install buffer but it didn't solve the error.

**Comment by facies** [comment]
I also add to change the following declaration in index.ts (blur was in small letter and couldn't be found).
import { Blur } from "./engine/BLUR";
Thanks!

**Comment by script-money** [comment]
> Thanks a lot for releasing this. I am experiencing the following error when I do the npm install
> 
> node_modules/keccak256/dist/keccak256.d.ts:4:67 - error TS2749: 'buffer.Buffer' refers to a value, but is being used as a type here. Did you mean 'typeof buffer.Buffer'?
> 
> I tried to do a npm install buffer but it didn't solve the error.

Can you try to modify tsconfig.ts?  refer: https://github.com/agea/CmisJS/issues/69

**Comment by script-money** [comment]
> I also had to change the following declaration in index.ts (blur was in small letter and couldn't be found). import { Blur } from "./engine/BLUR"; Thanks!

Yes, it's a typo error I will fix later

**Comment by facies** [comment]
> > Thanks a lot for releasing this. I am experiencing the following error when I do the npm install
> > node_modules/keccak256/dist/keccak256.d.ts:4:67 - error TS2749: 'buffer.Buffer' refers to a value, but is being used as a type here. Did you mean 'typeof buffer.Buffer'?
> > I tried to do a npm install buffer but it didn't solve the error.
> 
> Can you try to modify tsconfig.ts? refer: [agea/CmisJS#69](https://github.com/agea/CmisJS/issues/69) And try use node v18.

Thanks for your help, it is really appreciated fren. I already tried the tsconfig.ts edit without success but was able to install everything after upgrading node to v18.

Now I get the following error when i do a yarn start

[2023-02-16T17:01:54.827Z] Error: missing response (requestBody="{\"method\":\"eth_getBlockByNumber\",\"params\":[\"latest\",false],\"id\":42,\"jsonrpc\":\"2.0\"}", requestMethod="POST", serverError={"code":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY"}, url="https://rpc.flashbots.net", code=SERVER_ERROR, version=web/5.5.0)

I tried to set strict-ssl to false in .yarnc but it doesn't resolve the issue.

**Comment by script-money** [comment]
> UNABLE_TO_GET_ISSUER_CERT_LOCALLY

is `yarn config set "strict-ssl" false` or `npm config set strict-ssl false` work?

**Comment by facies** [comment]
> > UNABLE_TO_GET_ISSUER_CERT_LOCALLY
> 
> is `yarn config set "strict-ssl" false` or `npm config set strict-ssl false` work?

Thank you for following this and the suggestions. I already disabled ssl on both npm and yarn configs. Here is the result of the yarn config list command

info yarn config
{
  'version-tag-prefix': 'v',
  'version-git-tag': true,
  'version-commit-hooks': true,
  'version-git-sign': false,
  'version-git-message': 'v%s',
  'init-version': '1.0.0',
  'init-license': 'MIT',
  'save-prefix': '^',
  'bin-links': true,
  'ignore-scripts': false,
  'ignore-optional': false,
  registry: 'http://registry.npmjs.org/',
  'strict-ssl': false,
  'user-agent': 'yarn/1.22.19 npm/? node/v18.0.0 linux x64',
  enableStrictSsl: false,
  lastUpdateCheck: 1676564071429
}
info npm config
{
  registry: 'http://registry.npmjs.org/',
  'strict-ssl': false,
  globalconfig: '/etc/npmrc'
}

**Comment by script-money** [comment]
> > > UNABLE_TO_GET_ISSUER_CERT_LOCALLY
> > 
> > 
> > is `yarn config set "strict-ssl" false` or `npm config set strict-ssl false` work?
> 
> Thank you for following this and the suggestions. I already disabled ssl on both npm and yarn configs. Here is the result of the yarn config list command
> 
> info yarn config { 'version-tag-prefix': 'v', 'version-git-tag': true, 'version-commit-hooks': true, 'version-git-sign': false, 'version-git-message': 'v%s', 'init-version': '1.0.0', 'init-license': 'MIT', 'save-prefix': '^', 'bin-links': true, 'ignore-scripts': false, 'ignore-optional': false, registry: 'http://registry.npmjs.org/', 'strict-ssl': false, 'user-agent': 'yarn/1.22.19 npm/? node/v18.0.0 linux x64', enableStrictSsl: false, lastUpdateCheck: 1676564071429 } info npm config { registry: 'http://registry.npmjs.org/', 'strict-ssl': false, globalconfig: '/etc/npmrc' }

My config is `'strict-ssl': true`
What's your operation system version?

**Comment by facies** [comment]
> > > > UNABLE_TO_GET_ISSUER_CERT_LOCALLY
> > > 
> > > 
> > > is `yarn config set "strict-ssl" false` or `npm config set strict-ssl false` work?
> > 
> > 
> > Thank you for following this and the suggestions. I already disabled ssl on both npm and yarn configs. Here is the result of the yarn config list command
> > info yarn config { 'version-tag-prefix': 'v', 'version-git-tag': true, 'version-commit-hooks': true, 'version-git-sign': false, 'version-git-message': 'v%s', 'init-version': '1.0.0', 'init-license': 'MIT', 'save-prefix': '^', 'bin-links': true, 'ignore-scripts': false, 'ignore-optional': false, registry: 'http://registry.npmjs.org/', 'strict-ssl': false, 'user-agent': 'yarn/1.22.19 npm/? node/v18.0.0 linux x64', enableStrictSsl: false, lastUpdateCheck: 1676564071429 } info npm config { registry: 'http://registry.npmjs.org/', 'strict-ssl': false, globalconfig: '/etc/npmrc' }
> 
> My config is `'strict-ssl': true` What's your operation system version?

Yes thanks it was also my config at the beginning and I switched to false after seeing the error message.

I execute the script on a remote server and my OS is Debian 10. I also contacted my hosting company to see if they have an idea. Thanks again!

**Comment by facies** [comment]
Update after getting an answer from my hosting they advised to upgrade again Node at v18.13 and I was able to launch the script.

I now have this error : 

[2023-02-17T13:41:11.682Z] Error: TX #1 : execution reverted�y� Airdrop already claimed
    at checkSimulation

But I can see that the $blur have not been claimed nor transferred on the wallet. Do I need to change the data somewhere in the script depending on the wallet? Thank you again.

**Comment by facies** [comment]
Update 2: sorry I figured out that I have to replace the URL in blur.ts. After doing that I was able to claim the token and transfer it safely to its owner. He was so happy, thanks a lot for your time fren <3
